# Generated by Django 4.2.20 on 2025-04-10 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_label', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('inoculation_date', models.DateField()),
                ('num_bags', models.IntegerField()),
                ('contaminated_bags', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(default='incubation', max_length=50)),
                ('grow_room_entry_date', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
